---
- name: creating user
  hosts: all

  vars_prompt:
    - name: username
      prompt: what is the name of your user?
      private: no

    - name: sshkey
      prompt: what is their ssh public key?
      private: no

  tasks:
    - name: Print a debug message
      ansible.builtin.debug:
        msg: 'You will be adding {{ username }} with key {{ sshkey }}'

    - name: adding new users
      user:
        name: {{ username }}
        shell: /bin/bash

    - name: adding the public key
      ansible.posix.authorized_key:
        user: {{ username }}
        state: present
        key: {{ sshkey }}
