---
- name: creating user
  hosts: all
  become: yes
  tasks:
    - name: adding new users
      user:
        name: charles
        shell: /bin/bash
        password: "r3s3tm3!"

    - name: adding the public key
      ansible.posix.authorized_key:
        user: charles
        state: present
        key: "{{ lookup('file', '/home/charles/.ssh/id_rsa.pub') }}"
